name: Ruby RSpec Tests

on:
  push:
   branches:
   - main
  pull_request:
   branches:
     - main
     
  jobs:
    ruby-playwright-run:
     runs-on: ubuntu-latest

     steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Ruby
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: '3.2.3'
            bundler-cache: true

        - name: Setup Node
          uses: actions/setup-node@v4
          with:
            node-version: '20'

        - name: Install dependencies
          run: |
                gem install bundler
                bundle install

        - name: Install Playwright Browsers
          run: |
              npx playwright install-deps
              npx playwright install

        - name: Run RSpec tests
          env:
            CI: true
          run: bundle exec rspec
